### ISSUE TITLE
per-mode = "symbol" ignores quantity-product when no per is used

### ISSUE THREAD

**Issue by ludwig-austermann** [fenjalien/metro#12] opened 2023-12-14 01:10 UTC
Setting `per-mode = "symbol"` removes the quantity product.  Writing

```typst
23    num(number, e: e, pm: pm, separate-uncertainty: separate-uncertainty, separate-uncertainty-unit: if separate-uncertainty == "repeat" { u }, ..options)
24    quantity-product    // inserted
25    u
```

in `qty.typ` solved the issue in my case.

**Comment by fenjalien** [comment] 2023-12-15 00:45
I can't reproduce the bug you're experiencing, could you give a minimum example please?

```typ
#import "@preview/metro:0.1.1": *
#qty(2.67, "farad/s", per-mode: "symbol", quantity-product: sym.times)
```
gives me
![image](https://github.com/fenjalien/metro/assets/34489450/2ca932c4-37ea-42c9-ae75-32133b167544)

**Comment by ludwig-austermann** [comment] 2023-12-15 01:48
When writing
```typst
#import "@preview/metro:0.1.1": qty
#qty(1.23, "m", per-mode: "symbol")\
#qty(1.23, "m", per-mode: "symbol", quantity-product: sym.times)\
#qty(1.23, "m")\
#qty(1.23, "m/s", per-mode: "symbol")\
#qty(1.23, "m/s", per-mode: "symbol", quantity-product: sym.times)\
#qty(1.23, "m/s")
```
I obtain
![test(4)](https://github.com/fenjalien/metro/assets/12214171/a3461876-4d15-4479-a96d-ce1e1b9c60a7)

As the default `quantity-product` is a thin space, it is removed in the 1st and 2nd 'qty', when using no 'per'. The third one is the expected behaviour.

I encountered this bug, when I changed the styling of all 'qty''s via `metro-setup`. Btw, a further improvement would be, if the user could differentiate between
- `quantity-product` between number and unit, and
- `quantity-product` between units,
as my intention was to only customize the spacing in the first case.

**Comment by ludwig-austermann** [comment] 2023-12-15 01:49
I also noticed, that `#qty(1.23, "m m/s", per-mode: "symbol", quantity-product: sym.times)` produces some wrong result.

**Comment by fenjalien** [comment] 2024-01-31 15:40
Fixed as of https://github.com/fenjalien/metro/commit/94c4bc4550b0b4c12a7add494bf007b7231d0664

**Closed by fenjalien** 2024-01-31 15:40 UTC
Labels: bug
